MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    USE_FPN: True
    ANCHOR_SIZES: (128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16)
  ROI_BOX_HEAD:
    NUM_CLASSES: 9
DATASETS:
  TRAIN: ("chata_train", "chata_val")
  TEST: ("chata_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, )
  MAX_ITER: 400000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1